Eliminate LinkageError when passing a JsonPointer loaded by a different plugin
Because Jackson is shipped as a lib jar, external plugin fail to call
Model#find(JsonPointer):
 
```
java.lang.LinkageError: loader constraint violation: when resolving
method
"com.reprezen.swagedit.model.Model.find(Lcom/fasterxml/jackson/core/JsonPointer;)Lcom/reprezen/swagedit/model/AbstractNode;"
the class loader (instance of
org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current
class, and the class loader (instance of
org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's
defining class, com/reprezen/swagedit/model/Model, have different Class
objects for the type com/fasterxml/jackson/core/JsonPointer used in the
signature
```