ZEN-2716 RAPID-ML Editor Freezes caused by
java.lang.IllegalArgumentException: Illegal character in path at index
9: pathItems\ropeSwagger_address_fulldetails_smartystreets.yaml
	at java.net.URI.create(Unknown Source)
	at java.net.URI.resolve(Unknown Source)
	at
com.reprezen.swagedit.editor.hyperlinks.JsonReferenceHyperlinkDetector.getFile(JsonReferenceHyperlinkDetector.java:114)
	at
com.reprezen.swagedit.editor.hyperlinks.JsonReferenceHyperlinkDetector.doDetectExternalLink(JsonReferenceHyperlinkDetector.java:71)
	at
com.reprezen.swagedit.editor.hyperlinks.JsonReferenceHyperlinkDetector.doDetect(JsonReferenceHyperlinkDetector.java:55)