ZEN-3178 - expose JsonPointer as a String to prevent LinkageError
Calling #getPointer().toString() from outside of this plugin causes an
error:
java.lang.LinkageError: loader constraint violation: loader (instance of
org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously
initiated loading for a different type with name
"com/fasterxml/jackson/core/JsonPointer" 

It happens because SwagEdit uses Jackson shipped as a lib jar. We should
replace lib/jar for Jackson by an instance from Orbit repository, but
using a JsonPointer as a string for now.